package services.optout

import testUtils.UnitSpec
import org.scalatest.prop.TableDrivenPropertyChecks._


import scala.io.Source

class OptOutPropositionTest extends UnitSpec {

  //TODO name well
  "Parse opt out scenarios from tsv version" should {
    "return formatted scenarios" when {
      "read" in {
        //TODO comment on how to generate tsv file

        val tsvOptOut = Source.fromFile("OptOutReduced.tsv")

        val lines = tsvOptOut.getLines().drop(2)


        def parseOptionsPresented(option: String): Seq[String] = {
          option match {
            case "Nothing displayed" => Seq()
            case _ => option.replaceAll("\"", "").split("( and |, )").toSeq
          }
        }

        def formatOptionPresented(options: Seq[String]) = {
          "Seq(" ++ options.map(option => s"\"$option\"").mkString(", ") ++ ")"
        }

        def parseIsValid(valid: String): Boolean = {
          valid == "Allowed"
        }

        def parseCustomerIntent(intent: String): String = {
          intent.replaceAll("Customer wants to opt out from ", "")
        }

        def quote(input: String): String = {
          "\""++ input ++ "\""
        }

        // Print the extracted data
        lines.foreach(line => {
          val cells = line.split("\t").take(7)
         //println(cells.mkString("  --  "))
          println(s"(${quote(cells(0))}, ${quote(cells(1))}, ${quote(cells(2))}, ${quote(cells(3))}, ${formatOptionPresented(parseOptionsPresented(cells(4)))}, ${quote(parseCustomerIntent(cells(5)))}, ${parseIsValid(cells(6))}),")
        })

        // Close the CSV file
        tsvOptOut.close()
      }
    }
  }

  private val optOuts =
    Table(
      ("Crystallised", "CY-1", "CY", "CY+1", "Outcome", "Customer intent", "Valid"),  // First tuple defines column names
      ("N", "M", "M", "M", Seq(), "CY-1", false),
      ("Y", "M", "M", "M", Seq(), "CY-1", false),
      ("N", "M", "M", "M", Seq(), "CY", false),
      ("Y", "M", "M", "M", Seq(), "CY", false),
      ("N", "M", "M", "M", Seq(), "CY+1", false),
      ("Y", "M", "M", "M", Seq(), "CY+1", false),
      ("N", "M", "M", "", Seq(), "CY-1", false),
      ("Y", "M", "M", "", Seq(), "CY-1", false),
      ("N", "M", "M", "", Seq(), "CY", false),
      ("Y", "M", "M", "", Seq(), "CY", false),
      ("N", "M", "M", "", Seq(), "CY+1", false),
      ("Y", "M", "M", "", Seq(), "CY+1", false),
      ("N", "M", "M", "V", Seq("CY+1"), "CY-1", false),
      ("Y", "M", "M", "V", Seq("CY+1"), "CY-1", false),
      ("N", "M", "M", "V", Seq("CY+1"), "CY", false),
      ("Y", "M", "M", "V", Seq("CY+1"), "CY", false),
      ("N", "M", "M", "V", Seq("CY+1"), "CY+1", true),
      ("Y", "M", "M", "V", Seq("CY+1"), "CY+1", true),
      ("N", "M", "M", "A", Seq(), "CY-1", false),
      ("Y", "M", "M", "A", Seq(), "CY-1", false),
      ("N", "M", "M", "A", Seq(), "CY", false),
      ("Y", "M", "M", "A", Seq(), "CY", false),
      ("N", "M", "M", "A", Seq(), "CY+1", false),
      ("Y", "M", "M", "A", Seq(), "CY+1", false),
      ("N", "M", "V", "M", Seq("CY"), "CY-1", false),
      ("Y", "M", "V", "M", Seq("CY"), "CY-1", false),
      ("N", "M", "V", "M", Seq("CY"), "CY", true),
      ("Y", "M", "V", "M", Seq("CY"), "CY", true),
      ("N", "M", "V", "M", Seq("CY"), "CY+1", false),
      ("Y", "M", "V", "M", Seq("CY"), "CY+1", false),
      ("N", "M", "V", "", Seq("CY", "CY+1"), "CY-1", false),
      ("Y", "M", "V", "", Seq("CY", "CY+1"), "CY-1", false),
      ("N", "M", "V", "", Seq("CY", "CY+1"), "CY", true),
      ("Y", "M", "V", "", Seq("CY", "CY+1"), "CY", true),
      ("N", "M", "V", "", Seq("CY", "CY+1"), "CY+1", true),
      ("Y", "M", "V", "", Seq("CY", "CY+1"), "CY+1", true),
      ("N", "M", "V", "V", Seq("CY", "CY+1"), "CY-1", false),
      ("Y", "M", "V", "V", Seq("CY", "CY+1"), "CY-1", false),
      ("N", "M", "V", "V", Seq("CY", "CY+1"), "CY", true),
      ("Y", "M", "V", "V", Seq("CY", "CY+1"), "CY", true),
      ("N", "M", "V", "V", Seq("CY", "CY+1"), "CY+1", true),
      ("Y", "M", "V", "V", Seq("CY", "CY+1"), "CY+1", true),
      ("N", "M", "V", "A", Seq("CY"), "CY-1", false),
      ("Y", "M", "V", "A", Seq("CY"), "CY-1", false),
      ("N", "M", "V", "A", Seq("CY"), "CY", true),
      ("Y", "M", "V", "A", Seq("CY"), "CY", true),
      ("N", "M", "V", "A", Seq("CY"), "CY+1", false),
      ("Y", "M", "V", "A", Seq("CY"), "CY+1", false),
      ("N", "M", "A", "M", Seq(), "CY-1", false),
      ("Y", "M", "A", "M", Seq(), "CY-1", false),
      ("N", "M", "A", "M", Seq(), "CY", false),
      ("Y", "M", "A", "M", Seq(), "CY", false),
      ("N", "M", "A", "M", Seq(), "CY+1", false),
      ("Y", "M", "A", "M", Seq(), "CY+1", false),
      ("N", "M", "A", "", Seq(), "CY-1", false),
      ("Y", "M", "A", "", Seq(), "CY-1", false),
      ("N", "M", "A", "", Seq(), "CY", false),
      ("Y", "M", "A", "", Seq(), "CY", false),
      ("N", "M", "A", "", Seq(), "CY+1", false),
      ("Y", "M", "A", "", Seq(), "CY+1", false),
      ("N", "M", "A", "V", Seq("CY+1"), "CY-1", false),
      ("Y", "M", "A", "V", Seq("CY+1"), "CY-1", false),
      ("N", "M", "A", "V", Seq("CY+1"), "CY", false),
      ("Y", "M", "A", "V", Seq("CY+1"), "CY", false),
      ("N", "M", "A", "V", Seq("CY+1"), "CY+1", true),
      ("Y", "M", "A", "V", Seq("CY+1"), "CY+1", true),
      ("N", "M", "A", "A", Seq(), "CY-1", false),
      ("Y", "M", "A", "A", Seq(), "CY-1", false),
      ("N", "M", "A", "A", Seq(), "CY", false),
      ("Y", "M", "A", "A", Seq(), "CY", false),
      ("N", "M", "A", "A", Seq(), "CY+1", false),
      ("Y", "M", "A", "A", Seq(), "CY+1", false),
      ("N", "V", "M", "M", Seq("CY-1"), "CY-1", true),
      ("Y", "V", "M", "M", Seq(), "CY-1", false),
      ("N", "V", "M", "M", Seq("CY-1"), "CY", false),
      ("Y", "V", "M", "M", Seq(), "CY", false),
      ("N", "V", "M", "M", Seq("CY-1"), "CY+1", false),
      ("Y", "V", "M", "M", Seq(), "CY+1", false),
      ("N", "V", "M", "", Seq("CY-1"), "CY-1", true),
      ("Y", "V", "M", "", Seq(), "CY-1", false),
      ("N", "V", "M", "", Seq("CY-1"), "CY", false),
      ("Y", "V", "M", "", Seq(), "CY", false),
      ("N", "V", "M", "", Seq("CY-1"), "CY+1", false),
      ("Y", "V", "M", "", Seq(), "CY+1", false),
      ("N", "V", "M", "V", Seq("CY-1", "CY+1"), "CY-1", true),
      ("Y", "V", "M", "V", Seq("CY+1"), "CY-1", false),
      ("N", "V", "M", "V", Seq("CY-1", "CY+1"), "CY", false),
      ("Y", "V", "M", "V", Seq("CY+1"), "CY", false),
      ("N", "V", "M", "V", Seq("CY-1", "CY+1"), "CY+1", true),
      ("Y", "V", "M", "V", Seq("CY+1"), "CY+1", true),
      ("N", "V", "M", "A", Seq("CY-1"), "CY-1", true),
      ("Y", "V", "M", "A", Seq(), "CY-1", false),
      ("N", "V", "M", "A", Seq("CY-1"), "CY", false),
      ("Y", "V", "M", "A", Seq(), "CY", false),
      ("N", "V", "M", "A", Seq("CY-1"), "CY+1", false),
      ("Y", "V", "M", "A", Seq(), "CY+1", false),
      ("N", "V", "V", "M", Seq("CY-1", "CY"), "CY-1", true),
      ("Y", "V", "V", "M", Seq("CY"), "CY-1", false),
      ("N", "V", "V", "M", Seq("CY-1", "CY"), "CY", true),
      ("Y", "V", "V", "M", Seq("CY"), "CY", true),
      ("N", "V", "V", "M", Seq("CY-1", "CY"), "CY+1", false),
      ("Y", "V", "V", "M", Seq("CY"), "CY+1", false),
      ("N", "V", "V", "", Seq("CY-1", "CY", "CY+1"), "CY-1", true),
      ("Y", "V", "V", "", Seq("CY", "CY+1"), "CY-1", false),
      ("N", "V", "V", "", Seq("CY-1", "CY", "CY+1"), "CY", true),
      ("Y", "V", "V", "", Seq("CY", "CY+1"), "CY", true),
      ("N", "V", "V", "", Seq("CY-1", "CY", "CY+1"), "CY+1", true),
      ("Y", "V", "V", "", Seq("CY", "CY+1"), "CY+1", true),
      ("N", "V", "V", "V", Seq("CY-1", "CY", "CY+1"), "CY-1", true),
      ("Y", "V", "V", "V", Seq("CY", "CY+1"), "CY-1", false),
      ("N", "V", "V", "V", Seq("CY-1", "CY", "CY+1"), "CY", true),
      ("Y", "V", "V", "V", Seq("CY", "CY+1"), "CY", true),
      ("N", "V", "V", "V", Seq("CY-1", "CY", "CY+1"), "CY+1", true),
      ("Y", "V", "V", "V", Seq("CY", "CY+1"), "CY+1", true),
      ("N", "V", "V", "A", Seq("CY-1", "CY"), "CY-1", true),
      ("Y", "V", "V", "A", Seq("CY"), "CY-1", false),
      ("N", "V", "V", "A", Seq("CY-1", "CY"), "CY", true),
      ("Y", "V", "V", "A", Seq("CY"), "CY", true),
      ("N", "V", "V", "A", Seq("CY-1", "CY"), "CY+1", false),
      ("Y", "V", "V", "A", Seq("CY"), "CY+1", false),
      ("N", "V", "A", "M", Seq("CY-1"), "CY-1", true),
      ("Y", "V", "A", "M", Seq(), "CY-1", false),
      ("N", "V", "A", "M", Seq("CY-1"), "CY", false),
      ("Y", "V", "A", "M", Seq(), "CY", false),
      ("N", "V", "A", "M", Seq("CY-1"), "CY+1", false),
      ("Y", "V", "A", "M", Seq(), "CY+1", false),
      ("N", "V", "A", "", Seq("CY-1"), "CY-1", true),
      ("Y", "V", "A", "", Seq(), "CY-1", false),
      ("N", "V", "A", "", Seq("CY-1"), "CY", false),
      ("Y", "V", "A", "", Seq(), "CY", false),
      ("N", "V", "A", "", Seq("CY-1"), "CY+1", false),
      ("Y", "V", "A", "", Seq(), "CY+1", false),
      ("N", "V", "A", "V", Seq("CY-1", "CY+1"), "CY-1", true),
      ("Y", "V", "A", "V", Seq("CY+1"), "CY-1", false),
      ("N", "V", "A", "V", Seq("CY-1", "CY+1"), "CY", false),
      ("Y", "V", "A", "V", Seq("CY+1"), "CY", false),
      ("N", "V", "A", "V", Seq("CY-1", "CY+1"), "CY+1", true),
      ("Y", "V", "A", "V", Seq("CY+1"), "CY+1", true),
      ("N", "V", "A", "A", Seq("CY-1"), "CY-1", true),
      ("Y", "V", "A", "A", Seq(), "CY-1", false),
      ("N", "V", "A", "A", Seq("CY-1"), "CY", false),
      ("Y", "V", "A", "A", Seq(), "CY", false),
      ("N", "V", "A", "A", Seq("CY-1"), "CY+1", false),
      ("Y", "V", "A", "A", Seq(), "CY+1", false),
      ("N", "A", "M", "M", Seq(), "CY-1", false),
      ("Y", "A", "M", "M", Seq(), "CY-1", false),
      ("N", "A", "M", "M", Seq(), "CY", false),
      ("Y", "A", "M", "M", Seq(), "CY", false),
      ("N", "A", "M", "M", Seq(), "CY+1", false),
      ("Y", "A", "M", "M", Seq(), "CY+1", false),
      ("N", "A", "M", "", Seq(), "CY-1", false),
      ("Y", "A", "M", "", Seq(), "CY-1", false),
      ("N", "A", "M", "", Seq(), "CY", false),
      ("Y", "A", "M", "", Seq(), "CY", false),
      ("N", "A", "M", "", Seq(), "CY+1", false),
      ("Y", "A", "M", "", Seq(), "CY+1", false),
      ("N", "A", "M", "V", Seq("CY+1"), "CY-1", false),
      ("Y", "A", "M", "V", Seq("CY+1"), "CY-1", false),
      ("N", "A", "M", "V", Seq("CY+1"), "CY", false),
      ("Y", "A", "M", "V", Seq("CY+1"), "CY", false),
      ("N", "A", "M", "V", Seq("CY+1"), "CY+1", true),
      ("Y", "A", "M", "V", Seq("CY+1"), "CY+1", true),
      ("N", "A", "M", "A", Seq(), "CY-1", false),
      ("Y", "A", "M", "A", Seq(), "CY-1", false),
      ("N", "A", "M", "A", Seq(), "CY", false),
      ("Y", "A", "M", "A", Seq(), "CY", false),
      ("N", "A", "M", "A", Seq(), "CY+1", false),
      ("Y", "A", "M", "A", Seq(), "CY+1", false),
      ("N", "A", "V", "M", Seq("CY"), "CY-1", false),
      ("Y", "A", "V", "M", Seq("CY"), "CY-1", false),
      ("N", "A", "V", "M", Seq("CY"), "CY", true),
      ("Y", "A", "V", "M", Seq("CY"), "CY", true),
      ("N", "A", "V", "M", Seq("CY"), "CY+1", false),
      ("Y", "A", "V", "M", Seq("CY"), "CY+1", false),
      ("N", "A", "V", "", Seq("CY", "CY+1"), "CY-1", false),
      ("Y", "A", "V", "", Seq("CY", "CY+1"), "CY-1", false),
      ("N", "A", "V", "", Seq("CY", "CY+1"), "CY", true),
      ("Y", "A", "V", "", Seq("CY", "CY+1"), "CY", true),
      ("N", "A", "V", "", Seq("CY", "CY+1"), "CY+1", true),
      ("Y", "A", "V", "", Seq("CY", "CY+1"), "CY+1", true),
      ("N", "A", "V", "V", Seq("CY", "CY+1"), "CY-1", false),
      ("Y", "A", "V", "V", Seq("CY", "CY+1"), "CY-1", false),
      ("N", "A", "V", "V", Seq("CY", "CY+1"), "CY", true),
      ("Y", "A", "V", "V", Seq("CY", "CY+1"), "CY", true),
      ("N", "A", "V", "V", Seq("CY", "CY+1"), "CY+1", true),
      ("Y", "A", "V", "V", Seq("CY", "CY+1"), "CY+1", true),
      ("N", "A", "V", "A", Seq("CY"), "CY-1", false),
      ("Y", "A", "V", "A", Seq("CY"), "CY-1", false),
      ("N", "A", "V", "A", Seq("CY"), "CY", true),
      ("Y", "A", "V", "A", Seq("CY"), "CY", true),
      ("N", "A", "V", "A", Seq("CY"), "CY+1", false),
      ("Y", "A", "V", "A", Seq("CY"), "CY+1", false),
      ("N", "A", "A", "M", Seq(), "CY-1", false),
      ("Y", "A", "A", "M", Seq(), "CY-1", false),
      ("N", "A", "A", "M", Seq(), "CY", false),
      ("Y", "A", "A", "M", Seq(), "CY", false),
      ("N", "A", "A", "M", Seq(), "CY+1", false),
      ("Y", "A", "A", "M", Seq(), "CY+1", false),
      ("N", "A", "A", "", Seq(), "CY-1", false),
      ("Y", "A", "A", "", Seq(), "CY-1", false),
      ("N", "A", "A", "", Seq(), "CY", false),
      ("Y", "A", "A", "", Seq(), "CY", false),
      ("N", "A", "A", "", Seq(), "CY+1", false),
      ("Y", "A", "A", "", Seq(), "CY+1", false),
      ("N", "A", "A", "V", Seq("CY+1"), "CY-1", false),
      ("Y", "A", "A", "V", Seq("CY+1"), "CY-1", false),
      ("N", "A", "A", "V", Seq("CY+1"), "CY", false),
      ("Y", "A", "A", "V", Seq("CY+1"), "CY", false),
      ("N", "A", "A", "V", Seq("CY+1"), "CY+1", true),
      ("Y", "A", "A", "V", Seq("CY+1"), "CY+1", true),
      ("N", "A", "A", "A", Seq(), "CY-1", false),
      ("Y", "A", "A", "A", Seq(), "CY-1", false),
      ("N", "A", "A", "A", Seq(), "CY", false),
      ("Y", "A", "A", "A", Seq(), "CY", false),
      ("N", "A", "A", "A", Seq(), "CY+1", false),
      ("Y", "A", "A", "A", Seq(), "CY+1", false),
      ("N", "", "M", "M", Seq(), "CY-1", false),
      ("Y", "", "M", "M", Seq(), "CY-1", false),
      ("N", "", "M", "M", Seq(), "CY", false),
      ("Y", "", "M", "M", Seq(), "CY", false),
      ("N", "", "M", "M", Seq(), "CY+1", false),
      ("Y", "", "M", "M", Seq(), "CY+1", false),
      ("N", "", "M", "", Seq(), "CY-1", false),
      ("Y", "", "M", "", Seq(), "CY-1", false),
      ("N", "", "M", "", Seq(), "CY", false),
      ("Y", "", "M", "", Seq(), "CY", false),
      ("N", "", "M", "", Seq(), "CY+1", false),
      ("Y", "", "M", "", Seq(), "CY+1", false),
      ("N", "", "M", "V", Seq("CY+1"), "CY-1", false),
      ("Y", "", "M", "V", Seq("CY+1"), "CY-1", false),
      ("N", "", "M", "V", Seq("CY+1"), "CY", false),
      ("Y", "", "M", "V", Seq("CY+1"), "CY", false),
      ("N", "", "M", "V", Seq("CY+1"), "CY+1", true),
      ("Y", "", "M", "V", Seq("CY+1"), "CY+1", true),
      ("N", "", "M", "A", Seq(), "CY-1", false),
      ("Y", "", "M", "A", Seq(), "CY-1", false),
      ("N", "", "M", "A", Seq(), "CY", false),
      ("Y", "", "M", "A", Seq(), "CY", false),
      ("N", "", "M", "A", Seq(), "CY+1", false),
      ("Y", "", "M", "A", Seq(), "CY+1", false),
      ("N", "", "V", "M", Seq("CY"), "CY-1", false),
      ("Y", "", "V", "M", Seq("CY"), "CY-1", false),
      ("N", "", "V", "M", Seq("CY"), "CY", true),
      ("Y", "", "V", "M", Seq("CY"), "CY", true),
      ("N", "", "V", "M", Seq("CY"), "CY+1", false),
      ("Y", "", "V", "M", Seq("CY"), "CY+1", false),
      ("N", "", "V", "", Seq("CY", "CY+1"), "CY-1", false),
      ("Y", "", "V", "", Seq("CY", "CY+1"), "CY-1", false),
      ("N", "", "V", "", Seq("CY", "CY+1"), "CY", true),
      ("Y", "", "V", "", Seq("CY", "CY+1"), "CY", true),
      ("N", "", "V", "", Seq("CY", "CY+1"), "CY+1", true),
      ("Y", "", "V", "", Seq("CY", "CY+1"), "CY+1", true),
      ("N", "", "V", "V", Seq("CY", "CY+1"), "CY-1", false),
      ("Y", "", "V", "V", Seq("CY", "CY+1"), "CY-1", false),
      ("N", "", "V", "V", Seq("CY", "CY+1"), "CY", true),
      ("Y", "", "V", "V", Seq("CY", "CY+1"), "CY", true),
      ("N", "", "V", "V", Seq("CY", "CY+1"), "CY+1", true),
      ("Y", "", "V", "V", Seq("CY", "CY+1"), "CY+1", true),
      ("N", "", "V", "A", Seq("CY"), "CY-1", false),
      ("Y", "", "V", "A", Seq("CY"), "CY-1", false),
      ("N", "", "V", "A", Seq("CY"), "CY", true),
      ("Y", "", "V", "A", Seq("CY"), "CY", true),
      ("N", "", "V", "A", Seq("CY"), "CY+1", false),
      ("Y", "", "V", "A", Seq("CY"), "CY+1", false),
      ("N", "", "A", "M", Seq(), "CY-1", false),
      ("Y", "", "A", "M", Seq(), "CY-1", false),
      ("N", "", "A", "M", Seq(), "CY", false),
      ("Y", "", "A", "M", Seq(), "CY", false),
      ("N", "", "A", "M", Seq(), "CY+1", false),
      ("Y", "", "A", "M", Seq(), "CY+1", false),
      ("N", "", "A", "", Seq(), "CY-1", false),
      ("Y", "", "A", "", Seq(), "CY-1", false),
      ("N", "", "A", "", Seq(), "CY", false),
      ("Y", "", "A", "", Seq(), "CY", false),
      ("N", "", "A", "", Seq(), "CY+1", false),
      ("Y", "", "A", "", Seq(), "CY+1", false),
      ("N", "", "A", "V", Seq("CY+1"), "CY-1", false),
      ("Y", "", "A", "V", Seq("CY+1"), "CY-1", false),
      ("N", "", "A", "V", Seq("CY+1"), "CY", false),
      ("Y", "", "A", "V", Seq("CY+1"), "CY", false),
      ("N", "", "A", "V", Seq("CY+1"), "CY+1", true),
      ("Y", "", "A", "V", Seq("CY+1"), "CY+1", true),
      ("N", "", "A", "A", Seq(), "CY-1", false),
      ("Y", "", "A", "A", Seq(), "CY-1", false),
      ("N", "", "A", "A", Seq(), "CY", false),
      ("Y", "", "A", "A", Seq(), "CY", false),
      ("N", "", "A", "A", Seq(), "CY+1", false),
      ("Y", "", "A", "A", Seq(), "CY+1", false),
      ("N", "", "", "V", Seq("CY+1"), "CY+1", true),
      ("Y", "", "", "V", Seq("CY+1"), "CY+1", true),
      ("N", "", "", "M", Seq(), "CY+1", false),
      ("Y", "", "", "M", Seq(), "CY+1", false),
      ("N", "", "", "", Seq(), "CY", false),
      ("N", "", "", "", Seq(), "CY+1", false),
      ("N", "", "", "", Seq(), "CY-1", false),
      ("N", "", "", "A", Seq(), "CY", false),
      ("N", "", "", "A", Seq(), "CY+1", false),
      ("N", "", "", "A", Seq(), "CY-1", false),
      ("N", "", "", "M", Seq(), "CY", false),
      ("N", "", "", "M", Seq(), "CY-1", false),
      ("N", "", "", "V", Seq("CY+1"), "CY", false),
      ("N", "", "", "V", Seq("CY+1"), "CY-1", false),
      ("N", "A", "", "", Seq(), "CY", false),
      ("N", "A", "", "", Seq(), "CY+1", false),
      ("N", "A", "", "", Seq(), "CY-1", false),
      ("N", "A", "", "A", Seq(), "CY", false),
      ("N", "A", "", "A", Seq(), "CY+1", false),
      ("N", "A", "", "A", Seq(), "CY-1", false),
      ("N", "A", "", "M", Seq(), "CY", false),
      ("N", "A", "", "M", Seq(), "CY+1", false),
      ("N", "A", "", "M", Seq(), "CY-1", false),
      ("N", "A", "", "V", Seq("CY+1"), "CY", false),
      ("N", "A", "", "V", Seq("CY+1"), "CY+1", false),
      ("N", "A", "", "V", Seq("CY+1"), "CY-1", false),
      ("N", "M", "", "", Seq(), "CY", false),
      ("N", "M", "", "", Seq(), "CY+1", false),
      ("N", "M", "", "", Seq(), "CY-1", false),
      ("N", "M", "", "A", Seq(), "CY", false),
      ("N", "M", "", "A", Seq(), "CY+1", false),
      ("N", "M", "", "A", Seq(), "CY-1", false),
      ("N", "M", "", "M", Seq(), "CY", false),
      ("N", "M", "", "M", Seq(), "CY+1", false),
      ("N", "M", "", "M", Seq(), "CY-1", false),
      ("N", "M", "", "V", Seq("CY+1"), "CY", false),
      ("N", "M", "", "V", Seq("CY+1"), "CY+1", false),
      ("N", "M", "", "V", Seq("CY+1"), "CY-1", false),
      ("N", "V", "", "", Seq("CY-1"), "CY", false),
      ("N", "V", "", "", Seq("CY-1"), "CY+1", false),
      ("N", "V", "", "", Seq("CY-1"), "CY-1", false),
      ("N", "V", "", "A", Seq("CY-1"), "CY", false),
      ("N", "V", "", "A", Seq("CY-1"), "CY+1", false),
      ("N", "V", "", "A", Seq("CY-1"), "CY-1", false),
      ("N", "V", "", "M", Seq("CY-1"), "CY", false),
      ("N", "V", "", "M", Seq("CY-1"), "CY+1", false),
      ("N", "V", "", "M", Seq("CY-1"), "CY-1", false),
      ("N", "V", "", "V", Seq("CY-1", "CY+1"), "CY", false),
      ("N", "V", "", "V", Seq("CY-1", "CY+1"), "CY+1", false),
      ("N", "V", "", "V", Seq("CY-1", "CY+1"), "CY-1", false),
      ("Y", "", "", "", Seq(), "CY", false),
      ("Y", "", "", "", Seq(), "CY+1", false),
      ("Y", "", "", "", Seq(), "CY-1", false),
      ("Y", "", "", "A", Seq(), "CY", false),
      ("Y", "", "", "A", Seq(), "CY+1", false),
      ("Y", "", "", "A", Seq(), "CY-1", false),
      ("Y", "", "", "M", Seq(), "CY", false),
      ("Y", "", "", "M", Seq(), "CY-1", false),
      ("Y", "", "", "V", Seq("CY+1"), "CY", false),
      ("Y", "", "", "V", Seq("CY+1"), "CY-1", false),
      ("Y", "A", "", "", Seq(), "CY", false),
      ("Y", "A", "", "", Seq(), "CY+1", false),
      ("Y", "A", "", "", Seq(), "CY-1", false),
      ("Y", "A", "", "A", Seq(), "CY", false),
      ("Y", "A", "", "A", Seq(), "CY+1", false),
      ("Y", "A", "", "A", Seq(), "CY-1", false),
      ("Y", "A", "", "M", Seq(), "CY", false),
      ("Y", "A", "", "M", Seq(), "CY+1", false),
      ("Y", "A", "", "M", Seq(), "CY-1", false),
      ("Y", "A", "", "V", Seq("CY+1"), "CY", false),
      ("Y", "A", "", "V", Seq("CY+1"), "CY+1", false),
      ("Y", "A", "", "V", Seq("CY+1"), "CY-1", false),
      ("Y", "M", "", "", Seq(), "CY", false),
      ("Y", "M", "", "", Seq(), "CY+1", false),
      ("Y", "M", "", "", Seq(), "CY-1", false),
      ("Y", "M", "", "A", Seq(), "CY", false),
      ("Y", "M", "", "A", Seq(), "CY+1", false),
      ("Y", "M", "", "A", Seq(), "CY-1", false),
      ("Y", "M", "", "M", Seq(), "CY", false),
      ("Y", "M", "", "M", Seq(), "CY+1", false),
      ("Y", "M", "", "M", Seq(), "CY-1", false),
      ("Y", "M", "", "V", Seq("CY+1"), "CY", false),
      ("Y", "M", "", "V", Seq("CY+1"), "CY+1", false),
      ("Y", "M", "", "V", Seq("CY+1"), "CY-1", false),
      ("Y", "V", "", "", Seq(), "CY", false),
      ("Y", "V", "", "", Seq(), "CY+1", false),
      ("Y", "V", "", "", Seq(), "CY-1", false),
      ("Y", "V", "", "A", Seq(), "CY", false),
      ("Y", "V", "", "A", Seq(), "CY+1", false),
      ("Y", "V", "", "A", Seq(), "CY-1", false),
      ("Y", "V", "", "M", Seq(), "CY", false),
      ("Y", "V", "", "M", Seq(), "CY+1", false),
      ("Y", "V", "", "M", Seq(), "CY-1", false),
      ("Y", "V", "", "V", Seq("CY+1"), "CY", false),
      ("Y", "V", "", "V", Seq("CY+1"), "CY+1", false),
      ("Y", "V", "", "V", Seq("CY+1"), "CY-1", false),
    )


}
