echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/itsa-submission-integration/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/enable-income-sources-new-journey/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/enable-calendar-quarter-types/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/r7c-viewer-coding-out-txm-events/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/r7c-txm-events/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/time-machine-add-year/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/payment-history-refunds/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/mfa-credits-and-debits/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/what-you-owe-credit-amount/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/credits-refunds-repay/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/cut-over-credit/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/forecast-calculation/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/nav-bar/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/coding-out/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/payment-allocation/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/charge-history/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/iv-uplift/true"
echo "\n"
curl -X PUT "http://localhost:9081/report-quarterly/income-and-expenses/view/test-only/featureSwitch/itsa-submission-integration/true"
echo "\n"