/*
 * Copyright 2017 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package models

import play.api.libs.json.Json

sealed trait CalculationDataResponseModel

case class CalculationDataModel(
                                 incomeTaxYTD: BigDecimal,
                                 incomeTaxThisPeriod: BigDecimal,
                                 payFromAllEmployments: BigDecimal,
                                 benefitsAndExpensesReceived: BigDecimal,
                                 allowableExpenses: BigDecimal,
                                 payFromAllEmploymentsAfterExpenses: BigDecimal,
                                 shareSchemes: BigDecimal,
                                 profitFromSelfEmployment: BigDecimal,
                                 profitFromPartnerships: BigDecimal,
                                 profitFromUkLandAndProperty: BigDecimal,
                                 dividendsFromForeignCompanies: BigDecimal,
                                 foreignIncome: BigDecimal,
                                 trustsAndEstates: BigDecimal,
                                 interestReceivedFromUkBanksAndBuildingSocieties: BigDecimal,
                                 dividendsFromUkCompanies: BigDecimal,
                                 ukPensionsAndStateBenefits: BigDecimal,
                                 gainsOnLifeInsurance: BigDecimal,
                                 otherIncome: BigDecimal,
                                 totalIncomeReceived: BigDecimal,
                                 paymentsIntoARetirementAnnuity: BigDecimal,
                                 foreignTaxOnEstates: BigDecimal,
                                 incomeTaxRelief: BigDecimal,
                                 incomeTaxReliefReducedToMaximumAllowable: BigDecimal,
                                 annuities: BigDecimal,
                                 giftOfInvestmentsAndPropertyToCharity: BigDecimal,
                                 personalAllowance: BigDecimal,
                                 marriageAllowanceTransfer: BigDecimal,
                                 blindPersonAllowance: BigDecimal,
                                 blindPersonSurplusAllowanceFromSpouse: BigDecimal,
                                 incomeExcluded: BigDecimal,
                                 totalIncomeAllowancesUsed: BigDecimal,
                                 totalIncomeOnWhichTaxIsDue: BigDecimal,
                                 payPensionsExtender: BigDecimal,
                                 giftExtender: BigDecimal,
                                 extendedBR: BigDecimal,
                                 payPensionsProfitAtBRT: BigDecimal,
                                 incomeTaxOnPayPensionsProfitAtBRT: BigDecimal,
                                 payPensionsProfitAtHRT: BigDecimal,
                                 incomeTaxOnPayPensionsProfitAtHRT: BigDecimal,
                                 payPensionsProfitAtART: BigDecimal,
                                 incomeTaxOnPayPensionsProfitAtART: BigDecimal,
                                 netPropertyFinanceCosts: BigDecimal,
                                 interestReceivedAtStartingRate: BigDecimal,
                                 incomeTaxOnInterestReceivedAtStartingRate: BigDecimal,
                                 interestReceivedAtZeroRate: BigDecimal,
                                 incomeTaxOnInterestReceivedAtZeroRate: BigDecimal,
                                 interestReceivedAtBRT: BigDecimal,
                                 incomeTaxOnInterestReceivedAtBRT: BigDecimal,
                                 interestReceivedAtHRT: BigDecimal,
                                 incomeTaxOnInterestReceivedAtHRT: BigDecimal,
                                 interestReceivedAtART: BigDecimal,
                                 incomeTaxOnInterestReceivedAtART: BigDecimal,
                                 dividendsAtZeroRate: BigDecimal,
                                 incomeTaxOnDividendsAtZeroRate: BigDecimal,
                                 dividendsAtBRT: BigDecimal,
                                 incomeTaxOnDividendsAtBRT: BigDecimal,
                                 dividendsAtHRT: BigDecimal,
                                 incomeTaxOnDividendsAtHRT: BigDecimal,
                                 dividendsAtART: BigDecimal,
                                 incomeTaxOnDividendsAtART: BigDecimal,
                                 totalIncomeOnWhichTaxHasBeenCharged: BigDecimal,
                                 taxOnOtherIncome: BigDecimal,
                                 incomeTaxDue: BigDecimal,
                                 incomeTaxCharged: BigDecimal,
                                 deficiencyRelief: BigDecimal,
                                 topSlicingRelief: BigDecimal,
                                 ventureCapitalTrustRelief: BigDecimal,
                                 enterpriseInvestmentSchemeRelief: BigDecimal,
                                 seedEnterpriseInvestmentSchemeRelief: BigDecimal,
                                 communityInvestmentTaxRelief: BigDecimal,
                                 socialInvestmentTaxRelief: BigDecimal,
                                 maintenanceAndAlimonyPaid: BigDecimal,
                                 marriedCouplesAllowance: BigDecimal,
                                 marriedCouplesAllowanceRelief: BigDecimal,
                                 surplusMarriedCouplesAllowance: BigDecimal,
                                 surplusMarriedCouplesAllowanceRelief: BigDecimal,
                                 notionalTaxFromLifePolicies: BigDecimal,
                                 notionalTaxFromDividendsAndOtherIncome: BigDecimal,
                                 foreignTaxCreditRelief: BigDecimal,
                                 incomeTaxDueAfterAllowancesAndReliefs: BigDecimal,
                                 giftAidPaymentsAmount: BigDecimal,
                                 giftAidTaxDue: BigDecimal,
                                 capitalGainsTaxDue: BigDecimal,
                                 remittanceForNonDomiciles: BigDecimal,
                                 highIncomeChildBenefitCharge: BigDecimal,
                                 totalGiftAidTaxReduced: BigDecimal,
                                 incomeTaxDueAfterGiftAidReduction: BigDecimal,
                                 annuityAmount: BigDecimal,
                                 taxDueOnAnnuity: BigDecimal,
                                 taxCreditsOnDividendsFromUkCompanies: BigDecimal,
                                 incomeTaxDueAfterDividendTaxCredits: BigDecimal,
                                 nationalInsuranceContributionAmount: BigDecimal,
                                 nationalInsuranceContributionCharge: BigDecimal,
                                 nationalInsuranceContributionSupAmount: BigDecimal,
                                 nationalInsuranceContributionSupCharge: BigDecimal,
                                 totalClass4Charge: BigDecimal,
                                 nationalInsuranceClass1Amount: BigDecimal,
                                 nationalInsuranceClass2Amount: BigDecimal,
                                 nicTotal: BigDecimal,
                                 underpaidTaxForPreviousYears: BigDecimal,
                                 studentLoanRepayments: BigDecimal,
                                 pensionChargesGross: BigDecimal,
                                 pensionChargesTaxPaid: BigDecimal,
                                 totalPensionSavingCharges: BigDecimal,
                                 pensionLumpSumAmount: BigDecimal,
                                 pensionLumpSumRate: BigDecimal,
                                 statePensionLumpSumAmount: BigDecimal,
                                 remittanceBasisChargeForNonDomiciles: BigDecimal,
                                 additionalTaxDueOnPensions: BigDecimal,
                                 additionalTaxReliefDueOnPensions: BigDecimal,
                                 incomeTaxDueAfterPensionDeductions: BigDecimal,
                                 employmentsPensionsAndBenefits: BigDecimal,
                                 outstandingDebtCollectedThroughPaye: BigDecimal,
                                 payeTaxBalance: BigDecimal,
                                 cisAndTradingIncome: BigDecimal,
                                 partnerships: BigDecimal,
                                 ukLandAndPropertyTaxPaid: BigDecimal,
                                 foreignIncomeTaxPaid: BigDecimal,
                                 trustAndEstatesTaxPaid: BigDecimal,
                                 overseasIncomeTaxPaid: BigDecimal,
                                 interestReceivedTaxPaid: BigDecimal,
                                 voidISAs: BigDecimal,
                                 otherIncomeTaxPaid: BigDecimal,
                                 underpaidTaxForPriorYear: BigDecimal,
                                 totalTaxDeducted: BigDecimal,
                                 incomeTaxOverpaid: BigDecimal,
                                 incomeTaxDueAfterDeductions: BigDecimal,
                                 propertyFinanceTaxDeduction: BigDecimal,
                                 taxableCapitalGains: BigDecimal,
                                 capitalGainAtEntrepreneurRate: BigDecimal,
                                 incomeTaxOnCapitalGainAtEntrepreneurRate: BigDecimal,
                                 capitalGrainsAtLowerRate: BigDecimal,
                                 incomeTaxOnCapitalGainAtLowerRate: BigDecimal,
                                 capitalGainAtHigherRate: BigDecimal,
                                 incomeTaxOnCapitalGainAtHigherTax: BigDecimal,
                                 capitalGainsTaxAdjustment: BigDecimal,
                                 foreignTaxCreditReliefOnCapitalGains: BigDecimal,
                                 liabilityFromOffShoreTrusts: BigDecimal,
                                 taxOnGainsAlreadyCharged: BigDecimal,
                                 totalCapitalGainsTax: BigDecimal,
                                 incomeAndCapitalGainsTaxDue: BigDecimal,
                                 taxRefundedInYear: BigDecimal,
                                 unpaidTaxCalculatedForEarlierYears: BigDecimal,
                                 marriageAllowanceTransferAmount: BigDecimal,
                                 marriageAllowanceTransferRelief: BigDecimal,
                                 marriageAllowanceTransferMaximumAllowable: BigDecimal,
                                 nationalRegime:  String,
                                 allowance: BigDecimal,
                                 limitBRT: BigDecimal,
                                 limitHRT: BigDecimal,
                                 rateBRT: BigDecimal,
                                 rateHRT: BigDecimal,
                                 rateART: BigDecimal,
                                 limitAIA: BigDecimal,
                                 allowanceBRT: BigDecimal,
                                 interestAllowanceHRT: BigDecimal,
                                 interestAllowanceBRT: BigDecimal,
                                 dividendAllowance: BigDecimal,
                                 dividendBRT: BigDecimal,
                                 dividendHRT: BigDecimal,
                                 dividendART: BigDecimal,
                                 class2NICsLimit: BigDecimal,
                                 class2NICsPerWeek: BigDecimal,
                                 class4NICsLimitBR: BigDecimal,
                                 class4NICsLimitHR: BigDecimal,
                                 class4NICsBRT: BigDecimal,
                                 class4NICsHRT: BigDecimal,
                                 proportionAllowance: BigDecimal,
                                 proportionLimitBRT: BigDecimal,
                                 proportionLimitHRT: BigDecimal,
                                 proportionalTaxDue: BigDecimal,
                                 proportionInterestAllowanceBRT: BigDecimal,
                                 proportionInterestAllowanceHRT: BigDecimal,
                                 proportionDividendAllowance: BigDecimal,
                                 proportionPayPensionsProfitAtART: BigDecimal,
                                 proportionIncomeTaxOnPayPensionsProfitAtART: BigDecimal,
                                 proportionPayPensionsProfitAtBRT: BigDecimal,
                                 proportionIncomeTaxOnPayPensionsProfitAtBRT: BigDecimal,
                                 proportionPayPensionsProfitAtHRT: BigDecimal,
                                 proportionIncomeTaxOnPayPensionsProfitAtHRT: BigDecimal,
                                 proportionInterestReceivedAtZeroRate: BigDecimal,
                                 proportionIncomeTaxOnInterestReceivedAtZeroRate: BigDecimal,
                                 proportionInterestReceivedAtBRT: BigDecimal,
                                 proportionIncomeTaxOnInterestReceivedAtBRT: BigDecimal,
                                 proportionInterestReceivedAtHRT: BigDecimal,
                                 proportionIncomeTaxOnInterestReceivedAtHRT: BigDecimal,
                                 proportionInterestReceivedAtART: BigDecimal,
                                 proportionIncomeTaxOnInterestReceivedAtART: BigDecimal,
                                 proportionDividendsAtZeroRate: BigDecimal,
                                 proportionIncomeTaxOnDividendsAtZeroRate: BigDecimal,
                                 proportionDividendsAtBRT: BigDecimal,
                                 proportionIncomeTaxOnDividendsAtBRT: BigDecimal,
                                 proportionDividendsAtHRT: BigDecimal,
                                 proportionIncomeTaxOnDividendsAtHRT: BigDecimal,
                                 proportionDividendsAtART: BigDecimal,
                                 proportionIncomeTaxOnDividendsAtART: BigDecimal,
                                 proportionClass2NICsLimit: BigDecimal,
                                 proportionClass4NICsLimitBR: BigDecimal,
                                 proportionClass4NICsLimitHR: BigDecimal,
                                 proportionReducedAllowanceLimit: BigDecimal
                                 ) extends CalculationDataResponseModel

object CalculationDataModel {
  implicit val format = Json.format[CalculationDataModel]
}